[colors.bright]
black = "#b6bfbf"
blue = "#4169E1"
cyan = "#00FFFF"
green = "#7CFC00"
magenta = "#BF40BF"
red = "#EE4B2B"
white = "#b6bfbf"
yellow = "#e6cc0b"

[colors.normal]
black = "#1B1212"
blue = "#4169E1"
cyan = "#00FFFF"
green = "#7CFC00"
magenta = "#BF40BF"
red = "#EE4B2B"
white = "#b6bfbf"
yellow = "#e6cc0b"

[colors.primary]
background = "#000000"
foreground = "#d8e3e2"

[font]
size = 12.0

[font.italic]
family = "DejaVuSansM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "DejaVuSansM Nerd Font Mono"
style = "Regular"
